#nameerror 
try:
   print(x)
except NameError: 
   print("name error exception")